# -*- coding: utf-8 -*-
"""Entrainement LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vmN_d86U4RBI3kLk8EaUVGW1SopibQrm
"""

import requests
import time
import pandas as pd
import numpy as np
from functools import reduce
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
import random
import tensorflow as tf
import os

!pip install pymongo
!pip install flask pymongo
!pip install pyngrok
!pip install stable-baselines3

from datetime import datetime

start = int(datetime(2026, 6, 4, 16, 59).timestamp())
end = int(time.time())

print(datetime.fromtimestamp(start))
print(datetime.fromtimestamp(end))

# ==========================================================
# CONFIGURATION

# ==========================================================

url_base = "https://reload-kinsman-schnapps.ngrok-free.dev"
url = f"{url_base}/api/v1/query_range"

step  = "3m"

metrics = {
    "RAM":[
        "mongodb_ss_wt_cache_maximum_bytes_configured",
        "mongodb_ss_wt_cache_tracked_dirty_bytes_in_the_cache",
        "mongodb_ss_tcmalloc_generic_current_allocated_bytes",
        "mongodb_sys_memory_Cached_kb"
    ],

    "CPU":[
        "mongodb_ss_opcounters",
        "mongodb_ss_globalLock_currentQueue",
        "mongodb_ss_opLatencies_ops",
        "mongodb_sys_cpu_user_ms"
    ],

    "Network":[
        "mongodb_ss_network_bytesIn",
        "mongodb_ss_network_bytesOut",
        "mongodb_ss_network_numRequests"
    ],

    "Disk":[
        "mongodb_ss_wt_block_manager_bytes_read",
        "mongodb_ss_wt_block_manager_bytes_written",
        "mongodb_ss_wt_block_manager_blocks_written",
        "mongodb_ss_wt_block_manager_blocks_read",
        "mongodb_ss_wt_cache_pages_read_into_cache",
        "mongodb_ss_wt_cache_pages_written_from_cache"
    ],

    "EtatReplicaSet":[
        "mongodb_members_state",
        "mongodb_members_health",
        "mongodb_myState"
    ],

    "Synchronisation":[
        "mongodb_members_optimeDurableDate",
        "mongodb_members_optimeDate",
        "mongodb_members_syncSourceId"
    ],

    "Oplog":[
        "mongodb_oplog_stats_storageStats_size",
        "mongodb_ss_oplog_earliestOptime",
        "mongodb_ss_oplog_latestOptime"
    ],

    "Replication":[
        "mongodb_ss_metrics_repl_apply_ops",
        "mongodb_ss_metrics_repl_apply_batchSize",
        "mongodb_ss_metrics_repl_apply_batches_num",
        "mongodb_ss_metrics_repl_apply_batches_totalMillis"
    ],

    "Buffer":[
        "mongodb_ss_metrics_repl_buffer_count",
        "mongodb_ss_metrics_repl_buffer_maxSizeBytes",
        "mongodb_ss_metrics_repl_buffer_sizeBytes"
    ],

    "ReplicationNetwork":[
        "mongodb_ss_metrics_repl_network_getmores_num",
        "mongodb_ss_metrics_repl_network_ops",
        "mongodb_ss_metrics_repl_network_bytes",
        "mongodb_ss_metrics_repl_network_getmores_totalMillis"
    ]
}

# ==========================================================
# REGLES D'AGREGATION
# ==========================================================

aggregation_rules = {
    "mongodb_members_state": "max",
    "mongodb_members_health": "mean",
    "mongodb_myState": "max",

    "mongodb_members_optimeDate": "max",
    "mongodb_members_optimeDurableDate": "max",

    "mongodb_ss_oplog_latestOptime": "max",
    "mongodb_ss_oplog_earliestOptime": "min"
}

# ==========================================================
# RECUPERATION PROMETHEUS
# ==========================================================

def fetch_metric(metric_name):

    params = {
        "query": metric_name,
        "start": start,
        "end": end,
        "step": step
    }

    response = requests.get(
        url,
        params=params,
        timeout=20
    )

    response.raise_for_status()

    data = response.json()

    if data["status"] != "success":
        raise Exception(
            f"Erreur Prometheus : {metric_name}"
        )

    return data["data"]["result"]

# ==========================================================
# CONSTRUCTION DATAFRAME
# ==========================================================

metric_dataframes = []

for category, metric_list in metrics.items():

    for metric_name in metric_list:

        print(f"Collecte : {metric_name}")

        try:

            results = fetch_metric(metric_name)

        except Exception as e:

            print(f"Erreur {metric_name} : {e}")
            continue

        if len(results) == 0:

            print(f"Aucune donnée : {metric_name}")
            continue

        rows = []

        for serie in results:

            for ts, value in serie["values"]:

                try:
                    value = float(value)
                except:
                    value = np.nan

                rows.append({
                    "timestamp":
                        pd.to_datetime(
                            float(ts),
                            unit="s"
                        ),

                    metric_name:
                        value
                })


        df_metric = pd.DataFrame(rows)

        agg_method = aggregation_rules.get(
            metric_name,
            "mean"
        )

        df_metric = (
            df_metric
            .groupby("timestamp")[metric_name]
            .agg(agg_method)
            .reset_index()
        )

        metric_dataframes.append(
            df_metric
        )

# ==========================================================
# FUSION DE TOUTES LES METRIQUES
# ==========================================================

df_final = reduce(
    lambda left, right:
        pd.merge(
            left,
            right,
            on="timestamp",
            how="outer"
        ),
    metric_dataframes
)

df_final = (
    df_final
    .sort_values("timestamp")
    .reset_index(drop=True)
)

# ==========================================================
# SUPPRESSION DES DOUBLONS
# ==========================================================

df_final = (
    df_final
    .drop_duplicates(
        subset=["timestamp"]
    )
)

# ==========================================================
# ANALYSE DES VALEURS MANQUANTES
# ==========================================================

missing_percent = (
    df_final
    .isnull()
    .mean()
    * 100
).sort_values(
    ascending=False
)

print("\nValeurs manquantes (%)")
print(missing_percent)

# ==========================================================
# SUPPRIMER >50% DE NAN
# ==========================================================

cols_keep = (
    missing_percent[
        missing_percent < 50
    ]
    .index
)

df_final = df_final[
    cols_keep
]

print("\nShape après filtrage :")
print(df_final.shape)

# ==========================================================
# SAUVEGARDE
# ==========================================================

df_final.to_csv(
    "mongodb_dataset.csv",
    index=False
)
df_final.head()

features_df = pd.read_csv("mongodb_dataset.csv")
features_df = features_df.drop(columns=["timestamp"])

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

# Remplacement des NaN
imputer = SimpleImputer(strategy="median")

features = pd.DataFrame(
    imputer.fit_transform(features_df),
    columns=features_df.columns
)

# Suppression des doublons
df = features.drop_duplicates()

# Normalisation
scaler = MinMaxScaler()

scaled_data = scaler.fit_transform(df)

df_normalized = pd.DataFrame(
    scaled_data,
    columns=df.columns
)

print(df_normalized.head())

load_metrics = [
    #"RAM"
        "mongodb_ss_wt_cache_maximum_bytes_configured",
        "mongodb_ss_wt_cache_tracked_dirty_bytes_in_the_cache",
        "mongodb_ss_tcmalloc_generic_current_allocated_bytes",
        "mongodb_sys_memory_Cached_kb",

    #CPU":
        "mongodb_ss_opcounters",
        "mongodb_ss_globalLock_currentQueue",
        "mongodb_ss_opLatencies_ops",
        "mongodb_sys_cpu_user_ms",

    #"Network":
        "mongodb_ss_network_bytesIn",
        "mongodb_ss_network_bytesOut",
        "mongodb_ss_network_numRequests",

    #"Disk":
        "mongodb_ss_wt_block_manager_bytes_read",
        "mongodb_ss_wt_block_manager_bytes_written",
        "mongodb_ss_wt_block_manager_blocks_written",
        "mongodb_ss_wt_block_manager_blocks_read",
        "mongodb_ss_wt_cache_pages_read_into_cache",
        "mongodb_ss_wt_cache_pages_written_from_cache",

    #"EtatReplicaSet":
        "mongodb_members_state",
        "mongodb_members_health",
        "mongodb_myState",

    #"Synchronisation":
        "mongodb_members_optimeDurableDate",
        "mongodb_members_optimeDate",
        "mongodb_members_syncSourceId",

    #"Oplog":
        "mongodb_oplog_stats_storageStats_size",
        "mongodb_ss_oplog_earliestOptime",
        "mongodb_ss_oplog_latestOptime",

    #"Replication":
        "mongodb_ss_metrics_repl_apply_ops",
        "mongodb_ss_metrics_repl_apply_batchSize",
        "mongodb_ss_metrics_repl_apply_batches_num",
        "mongodb_ss_metrics_repl_apply_batches_totalMillis",

    #"Buffer":
        "mongodb_ss_metrics_repl_buffer_count",
        "mongodb_ss_metrics_repl_buffer_maxSizeBytes",
        "mongodb_ss_metrics_repl_buffer_sizeBytes",

    #"ReplicationNetwork":
        "mongodb_ss_metrics_repl_network_getmores_num",
        "mongodb_ss_metrics_repl_network_ops",
        "mongodb_ss_metrics_repl_network_bytes",
        "mongodb_ss_metrics_repl_network_getmores_totalMillis"
]

features_df = df_normalized[load_metrics]

from sklearn.decomposition import PCA
import pandas as pd
import numpy as np

pca = PCA(n_components=1)

pca.fit(features_df)

weights = np.abs(
    pca.components_[0]
)

weights = weights / weights.sum()

weights_df = pd.DataFrame({
    "Metric": features_df.columns,
    "Weight": weights
})

weights_df = weights_df.sort_values(
    by="Weight",
    ascending=False
)
weights_df.to_csv("pca_weights.csv", index=False)
print(weights_df)

load_score = np.dot(
    features_df.values,
    weights
)

df_normalized["LoadScore"] = load_score

q1 = df_normalized["LoadScore"].quantile(0.33)
q2 = df_normalized["LoadScore"].quantile(0.66)

def classify_load(score):

    if score <= q1:
        return "Faible"

    elif score <= q2:
        return "Moyenne"

    else:
        return "Elevee"

df_normalized["LoadClass"] = (
    df_normalized["LoadScore"]
    .apply(classify_load)
)

print(
    df_normalized["LoadClass"]
    .value_counts()
)

df_normalized= df_normalized.drop(columns=["LoadClass"])

df_normalized.head(10)

y=df_normalized["LoadScore"]
X = df_normalized.iloc[:, :-1]

load = df_normalized["LoadScore"].values

X = []
y = []

sequence_length = 20

for i in range(sequence_length, len(load)):

    X.append(
        load[i-sequence_length:i]
    )

    y.append(
        load[i]
    )

X = np.array(X)
y = np.array(y)

X = X.reshape(
    X.shape[0],
    X.shape[1],
    1
)
split = int(len(X) * 0.8)

X_train = X[:split]
X_test  = X[split:]

y_train = y[:split]
y_test  = y[split:]

print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

SEED = 42

os.environ["PYTHONHASHSEED"] = str(SEED)

random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

def create_model(learning_rate):

    model = Sequential()

    model.add(
        LSTM(
            units=64,
            input_shape=(
                X_train.shape[1],
                X_train.shape[2]
            )
        )
    )

    model.add(
        Dense(
            32,
            activation="relu"
        )
    )

    model.add(Dense(1))

    model.compile(
        optimizer=Adam(
            learning_rate=learning_rate
        ),
        loss="mse"
    )

    return model

learning_rates = [0.1,0.01, 0.001, 0.0001]

batch_sizes = [16, 32, 64]

epochs_list = [10,20, 50, 100]

best_mse = np.inf

best_params = None

best_model = None


for lr in learning_rates:

    for batch_size in batch_sizes:

        for epochs in epochs_list:

            print(
                f"Test : lr={lr}, "
                f"batch={batch_size}, "
                f"epochs={epochs}"
            )

            model = create_model(lr)

            history = model.fit(
                X_train,
                y_train,
                validation_split=0.2,
                epochs=epochs,
                batch_size=batch_size,
                verbose=0
            )

            y_pred = model.predict(
                X_test,
                verbose=0
            )

            mse = mean_squared_error(
                y_test,
                y_pred
            )

            print("MSE =", mse)

            if mse < best_mse:

                best_mse = mse

                best_params = {

                    "learning_rate": lr,

                    "batch_size": batch_size,

                    "epochs": epochs

                }

                best_model = model
                best_history = history

print("\nMeilleurs paramètres :")

print(best_params)

print("\nMeilleur MSE :")

print(best_mse)

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

y_pred = best_model.predict(X_test)

mse = mean_squared_error(
    y_test,
    y_pred
)

mae = mean_absolute_error(
    y_test,
    y_pred
)

rmse = np.sqrt(mse)

r2 = r2_score(
    y_test,
    y_pred
)

print("MSE :", mse)

print("MAE :", mae)

print("RMSE :", rmse)

print("R² :", r2)

import matplotlib.pyplot as plt
import pandas as pd

results = pd.DataFrame({
    "Metric": ["MSE", "MAE", "RMSE", "R²"],
    "Value": [mse, mae, rmse, r2]
})

plt.figure(figsize=(9,5))

bars = plt.bar(
    results["Metric"],
    results["Value"]
)

for bar in bars:
    plt.annotate(
        f"{bar.get_height():.4f}",
        xy=(bar.get_x() + bar.get_width()/2,
            bar.get_height()),
        xytext=(0,5),
        textcoords="offset points",
        ha='center'
    )

plt.title(
    "Évaluation du modèle LSTM",
    fontsize=16
)

plt.xlabel("Métriques")
plt.ylabel("Valeur")
plt.grid(True, axis='y', linestyle='--')

plt.show()

best_model.save(
    "best_lstm_model.keras"
)

y_predit= model.predict(X)
y_predit[:10,:]

df_rl = df_normalized.iloc[sequence_length:].copy()

df_rl["charge_predit"] = y_predit.flatten()
print(df_rl.shape)
print(y_predit.shape)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))
plt.plot(df_rl["LoadScore"].values, label="Charge réelle")
plt.plot(df_rl["charge_predit"].values, label="Charge prédite")
plt.legend()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.plot(
    best_history.history["loss"]
)

plt.title("Loss du modèle LSTM")

plt.xlabel("Epoch")

plt.ylabel("MSE Loss")

plt.grid(True)

plt.show()

from sklearn.metrics import r2_score

r2 = r2_score(df_rl["LoadScore"], df_rl["charge_predit"])
print(r2)

df

from google.colab import drive
drive.mount('/content/drive')

# LSTM
best_model.save(
    "/content/drive/MyDrive/Colab Notebooks/best_lstm_model.keras"
)

# Poids PCA
weights_df.to_csv(
    "/content/drive/MyDrive/Colab Notebooks/pca_weights.csv",
    index=False
)