# -*- coding: utf-8 -*-
"""ppoamelior.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBpCT3m22cjAnATzS7y_aTB1n2I9bFBd
"""

!pip install -U stable-baselines3 gymnasium

from google.colab import drive
drive.mount('/content/drive')
from tensorflow.keras.models import load_model
import pandas as pd


weights_df = pd.read_csv( "/content/drive/MyDrive/Colab Notebooks/pca_weights.csv")

best_lstm_model = load_model(
    "/content/drive/MyDrive/Colab Notebooks/best_lstm_model.keras")



METRICS = [
    #"RAM"
        "mongodb_ss_wt_cache_maximum_bytes_configured",
        "mongodb_ss_wt_cache_tracked_dirty_bytes_in_the_cache",
        "mongodb_ss_tcmalloc_generic_current_allocated_bytes",
        "mongodb_sys_memory_Cached_kb",

    #CPU":
        "mongodb_ss_opcounters",
        "mongodb_ss_globalLock_currentQueue",
        "mongodb_ss_opLatencies_ops",
        "mongodb_sys_cpu_user_ms",

    #"Network":
        "mongodb_ss_network_bytesIn",
        "mongodb_ss_network_bytesOut",
        "mongodb_ss_network_numRequests",

    #"Disk":
        "mongodb_ss_wt_block_manager_bytes_read",
        "mongodb_ss_wt_block_manager_bytes_written",
        "mongodb_ss_wt_block_manager_blocks_written",
        "mongodb_ss_wt_block_manager_blocks_read",
        "mongodb_ss_wt_cache_pages_read_into_cache",
        "mongodb_ss_wt_cache_pages_written_from_cache",

    #"EtatReplicaSet":
        "mongodb_members_state",
        "mongodb_members_health",
        "mongodb_myState",

    #"Synchronisation":
        "mongodb_members_optimeDurableDate",
        "mongodb_members_optimeDate",
        "mongodb_members_syncSourceId",

    #"Oplog":
        "mongodb_oplog_stats_storageStats_size",
        "mongodb_ss_oplog_earliestOptime",
        "mongodb_ss_oplog_latestOptime",

    #"Replication":
        "mongodb_ss_metrics_repl_apply_ops",
        "mongodb_ss_metrics_repl_apply_batchSize",
        "mongodb_ss_metrics_repl_apply_batches_num",
        "mongodb_ss_metrics_repl_apply_batches_totalMillis",

    #"Buffer":
        "mongodb_ss_metrics_repl_buffer_count",
        "mongodb_ss_metrics_repl_buffer_maxSizeBytes",
        "mongodb_ss_metrics_repl_buffer_sizeBytes",

    #"ReplicationNetwork":
        "mongodb_ss_metrics_repl_network_getmores_num",
        "mongodb_ss_metrics_repl_network_ops",
        "mongodb_ss_metrics_repl_network_bytes",
        "mongodb_ss_metrics_repl_network_getmores_totalMillis"
]

weights_df = weights_df["Weight"].to_numpy()

from stable_baselines3 import PPO
import gymnasium as gym
from gymnasium import spaces
import numpy as np
import requests

class MongoReplicaEnv1(gym.Env):

    def __init__(self):

        super().__init__()
        self.episode_rewards = []
        self.real_loads = []
        self.pred_loads = []
        self.actions_taken = []
        self.current_step = 0
        self.max_steps = 50

        self.actions = {0: "Do Nothing",

              1: "Add Secondary Node" ,

              2: "Remove Secondary Node",

              3: "Increase Oplog Size",

              4: "Decrease Oplog Size",

              5: "Enable ChainingAllowed",

              6: "Disable ChainingAllowed",

              7: "StepDown Primary",

              8: "Add Arbiter",

              9: "Remove Arbiter"

          }

        self.action_space = spaces.Discrete(
            len(self.actions)
        )

        STATE_DIM = len(self.get_state()[0])

        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(STATE_DIM,),
            dtype=np.float32
        )
    def get_state(self):

        r = requests.get("https://reload-kinsman-schnapps.ngrok-free.dev/get_state", timeout=15)

        if r.status_code != 200:
            raise RuntimeError(
                f"Server returned {r.status_code}\n{r.text}"
            )

        try:
            data = r.json()
        except Exception:
            raise RuntimeError(
                f"Invalid JSON returned by server:\n{r.text}"
            )

        metric_values = np.array(
            data["metrics"],
            dtype=np.float32
        )

        real_load = np.sum(
            metric_values * weights_df
        )

        real_load = float(real_load)

        X_lstm = metric_values.reshape(
            1,
            len(metric_values)
        )

        prediction = best_lstm_model.predict(
            X_lstm,
            verbose=0
        )

        predicted_load = prediction.item()

        state = np.concatenate([
            metric_values,
            [real_load],
            [predicted_load]
        ])
        state = np.array(
            state,
            dtype=np.float32
        )
        smin = state.min()
        smax = state.max()

        if smax > smin:

            state = (
                state - smin
            ) / (
                smax - smin
            )
        else:

            state = np.zeros_like(
                state
            )

        return state, real_load, predicted_load
    def get_replica_status(self):

        r = requests.get(
            "https://reload-kinsman-schnapps.ngrok-free.dev/replica-status",
            timeout=15
        )

        print("Status =", r.status_code)
        print("Response =", r.text)

        if r.status_code != 200:
            raise RuntimeError(
                f"HTTP {r.status_code}\n{r.text}"
            )

        try:
            return r.json()

        except Exception:

            raise RuntimeError(
                f"Invalid JSON:\n{r.text}"
            )

    def safety_layer(self, action):

        status = self.get_replica_status()

        nb_primary = status["primary"]
        nb_secondary = status["secondary"]
        nb_arbiter = status["arbiter"]

        blocked = False

        if action == 2:

            if nb_secondary <= 1:
                blocked = True

        elif action == 7:

            if nb_secondary == 0:
                blocked = True

        elif action == 9:

            if nb_arbiter <= 1:
                blocked = True

        if blocked:
            return 0, True

        return action, False
    def apply_action(self, action_id):

        r = requests.post(
            "https://reload-kinsman-schnapps.ngrok-free.dev/apply-action",
            json={"action": int(action_id)},
            timeout=15
        )

        print(r.status_code)
        print(r.text)

        if r.status_code != 200:
            raise RuntimeError(r.text)


    def compute_reward(self,load_before,load_after,pred_before,pred_after):

        reward = (
            0.7*(load_before - load_after)
            +
            0.3*(pred_before - pred_after)
        )

        return float(reward)
    def reset(self, seed=None, options=None):

        super().reset(seed=seed)

        self.current_step = 0

        state, _, _ = self.get_state()

        return state.astype(np.float32), {}

    def step(self, action):
        action_id = int(action)
        state_before, load_before, pred_before = self.get_state()


        safe_action, blocked = self.safety_layer(
            action_id
        )

        self.apply_action(
            safe_action
        )

        # délai pour laisser l'effet apparaître
        import time
        time.sleep(15)

        state_after, load_after, pred_after = self.get_state()

        reward = self.compute_reward(load_before,load_after,pred_before,pred_after)
        if blocked:

           reward -= 5
        done = False

        info = {
            "action": action_id,
            "load_before": load_before,
            "load_after": load_after
        }
        self.episode_rewards.append(reward)

        self.real_loads.append(load_after)

        self.pred_loads.append(pred_after)

        self.actions_taken.append(action_id)
        self.current_step += 1
        done = (
            self.current_step >= self.max_steps
        )

        return (
            state_after.astype(np.float32),
            reward,
            done,
            False,
            info
        )

from stable_baselines3 import PPO

env = MongoReplicaEnv1()

model = PPO(
    "MlpPolicy",
    env,
    device="cpu",
    learning_rate=3e-4,
    n_steps=32,
    batch_size=32,
    gamma=0.99,
    gae_lambda=0.95,
    clip_range=0.2,
    verbose=1
)

model.learn(
    total_timesteps=100
)

model.save(
    "ppo_mongodb"

)



import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# ==========================
# Reward brut
# ==========================
episode_rewards = env.episode_rewards
real_loads = env.real_loads
pred_loads = env.pred_loads
actions_taken = env.actions_taken


plt.figure(figsize=(12,5))
plt.plot(episode_rewards)
plt.title("Reward par épisode")
plt.xlabel("Episode")
plt.ylabel("Reward")
plt.grid()
plt.show()


# ==========================
# Reward moyenne glissante
# ==========================

window = 20

moving_avg = (
    pd.Series(episode_rewards)
    .rolling(window)
    .mean()
)

plt.figure(figsize=(12,5))
plt.plot(moving_avg)
plt.title(f"Reward moyenne glissante ({window} épisodes)")
plt.xlabel("Episode")
plt.ylabel("Reward moyen")
plt.grid()
plt.show()


# ==========================
# Charge réelle
# ==========================

plt.figure(figsize=(12,5))
plt.plot(real_loads)
plt.title("Charge réelle du Replica Set")
plt.xlabel("Episode")
plt.ylabel("Load")
plt.grid()
plt.show()


# ==========================
# Charge prédite par LSTM
# ==========================

plt.figure(figsize=(12,5))
plt.plot(pred_loads)
plt.title("Charge prédite par LSTM")
plt.xlabel("Episode")
plt.ylabel("Predicted Load")
plt.grid()
plt.show()



# ==========================
# Reward cumulée
# ==========================

cumulative_reward = np.cumsum(
    episode_rewards
)

plt.figure(figsize=(12,5))
plt.plot(cumulative_reward)

plt.title("Reward cumulée")
plt.xlabel("Episode")
plt.ylabel("Cumulative Reward")

plt.grid()

plt.show()


# ==========================
# Distribution des actions
# ==========================

action_counts = pd.Series(
    actions_taken
).value_counts().sort_index()

plt.figure(figsize=(12,5))

plt.bar(
    action_counts.index,
    action_counts.values
)

plt.title("Distribution des actions PPO")
plt.xlabel("Action")
plt.ylabel("Nombre de sélections")

plt.grid(axis="y")

plt.show()



window = 30

smooth_reward = (
    pd.Series(episode_rewards)
    .rolling(window)
    .mean()
)

plt.figure(figsize=(14,6))

plt.plot(
    smooth_reward,
    linewidth=3
)

plt.title(
    "Convergence de PPO durant l'entraînement"
)

plt.xlabel("Episodes")
plt.ylabel("Reward moyenne")

plt.grid()

plt.show()